BEHAVIORAL_LOW_MAX = 13
BEHAVIORAL_MEDIUM_MAX = 22
BEHAVIORAL_HIGH_MIN_TOLERANCE = 3
BEHAVIORAL_HIGH_MIN_PREFERENCE = 3
RISK_PERCEPTION_MAX_WITH_LOW_KNOWLEDGE = 3
LOW_KNOWLEDGE_THRESHOLD = 2

KNOWLEDGE_SCORE_MAP = {
    0: 1,
    1: 2,
    2: 3,
    3: 4,
}

SEVERE_CONFLICT_TOLERANCE_MIN = 4
SEVERE_CONFLICT_PREFERENCE_MIN = 4
SEVERE_CONFLICT_COMPOSURE_MAX = 2

REVERSE_CONFLICT_TOLERANCE_MAX = 2
REVERSE_CONFLICT_PREFERENCE_MAX = 2
REVERSE_CONFLICT_COMPOSURE_MIN = 5

RISK_LEVEL_ORDER = {'LOW': 1, 'MEDIUM': 2, 'HIGH': 3}
RISK_LEVEL_FROM_ORDER = {1: 'LOW', 2: 'MEDIUM', 3: 'HIGH'}